### ISSUE TITLE
Enabling HA after Creation - Fails - Does not first detach spoke from transit

### ISSUE THREAD

**Issue by bhp-aviatrix** [terraform-aviatrix-modules/terraform-aviatrix-mc-spoke#10]
If a spoke is created without hagw enabled, and at a later date - ha is enabled (and terraform apply rerun), the hagw is not created. 

module.mc-spoke["spoke5"].aviatrix_spoke_gateway.default: Still modifying... [id=bhp-mcna-lab-aws-use2-remotes, 10s elapsed]
╷
│ Error: failed to enable HA Aviatrix Spoke Gateway: rest API enable_spoke_ha Post failed: Error: bhp-mcna-lab-aws-use2-remotes is attached to bhp-mcna-lab-aws-use2-transit, detach it first.
│ 
│   with module.mc-spoke["spoke5"].aviatrix_spoke_gateway.default,
│   on .terraform/modules/mc-spoke/main.tf line 36, in resource "aviatrix_spoke_gateway" "default":
│   36: resource "aviatrix_spoke_gateway" "default" {
│ 
╵

**Comment by Dennizz** [comment]
Addressed in 1.3.2 (requires Terraform version 1.2.0)
