### ISSUE TITLE
Please update document where using existing vpc for spoke deployment, the format of vNet ID in Azure

### ISSUE THREAD

**Issue by jye-aviatrix** [terraform-aviatrix-modules/terraform-aviatrix-mc-spoke#18]
The format of vNet ID in Azure should be:
<vnet_name>:<resource_group_name>:<vnet_guid>

<img width="708" alt="image" src="https://github.com/terraform-aviatrix-modules/terraform-aviatrix-mc-spoke/assets/93721751/c63d5a51-2c57-499c-a01e-8d270a69d79e">

Above example should have this vpc_id:
aviatrix-vnet:Aviatrix:de5bd22f-1c53-45c4-87f5-a0a4b40cd103

It's time consuming to reverse engineer this each time, would be easier to be in the document

**Comment by Dennizz** [comment]
Updated the Azure examples
