### ISSUE TITLE
module fails with single gateway / single pair of subnets

### ISSUE THREAD

**Issue by rnxrx** [terraform-aviatrix-modules/terraform-aviatrix-mc-spoke#19]
Module declaration:

module "sp-aws-us-east-1" {
    count                          = 1
    source                        = "terraform-aviatrix-modules/mc-spoke/aviatrix"
    attached                     = "true"
    name                           = "sp-aws-us-east-1"
    cloud                           = "AWS"
    version                        = "1.6.3"
    instance_size             = "t3.medium"
    ha_gw                         = "false"
    cidr                              = "10.0.0.0/23"
    subnet_pairs               = 1
    subnet_size                 = 25
    account                       = "aws_admin"
    region                          = "us-east-1"
    insane_mode               = "true"
    enable_max_performance        = "false"
    inspection                    = "true"
    transit_gw                   = "tr-aws-us-east-1"
    depends_on                = [ module.transit-peering ]
}

Error: 

module.sp-aws-us-east-1[0].aviatrix_spoke_gateway.default: Refreshing state... [id=sp-aws-us-east-1]
╷
│ Error: Invalid function argument
│ 
│   on .terraform/modules/sp-aws-us-east-1/locals.tf line 82, in locals:
│   82:     aws = local.cloud == "aws" ? (var.use_existing_vpc ? [] : slice(aviatrix_vpc.default[0].public_subnets.*.cidr, 2, length(aviatrix_vpc.default[0].public_subnets))) : null #Get the rest of the public subnets, minus the first 2.
│     ├────────────────
│     │ while calling slice(list, start_index, end_index)
│ 
│ Invalid value for "start_index" parameter: start index must not be greater than the length of the list.
╵

suspicion is that a non-HA deployment with a single pair of subnets will only have 2 public which yields an invalid index

**Comment by Dennizz** [comment]
Please test against patch in main branch by changing your module source to:

```
module "sp-aws-us-east-1" {
source = "git::https://github.com/terraform-aviatrix-modules/terraform-aviatrix-mc-spoke"
...

}
```

And report if this resolved your issue.

**Comment by Dennizz** [comment]
Patch will be rolled up in next release.
