### ISSUE TITLE
Module does not exit, terraform keeps waiting forever for the module to return

### ISSUE THREAD

**Issue by gitet** [terraform-aviatrix-modules/terraform-aviatrix-mc-spoke#20]
Hi - I am trying to build a test-spoke VNET in an existing resource group.

**PROBLEM:** The module will deploy the resources correctly, but the `terraform apply` stage refuses to exit - terraform keeps waiting for the module to return.  

Tail of console output (TF_LOG=TRACE) looks like this:

```text
2023-08-15T10:04:05.776+0200 [TRACE] dag/walk: vertex "module.aviatrix_test_spoke (close)" is waiting for "module.aviatrix_test_spoke.aviatrix_spoke_gateway.default"
2023-08-15T10:04:05.778+0200 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/aviatrixsystems/aviatrix\"] (close)" is waiting for "module.aviatrix_test_spoke.aviatrix_spoke_gateway.default"
module.aviatrix_test_spoke.aviatrix_spoke_gateway.default: Still creating... [49m31s elapsed]
```
The VNET, subnets, route tables and gateways are all there in the resource group, but the module will not finish to completion.

Execution environment:
terraform version: 1.5.5
aviatrix provider: 3.1.1
controller version: 7.1.1710

Code snippet that produces the issue:

```terraform
module "aviatrix_test_spoke" {
  source  = "terraform-aviatrix-modules/mc-spoke/aviatrix"
  version = "1.6.3"

  cloud            = "Azure"
  name             = "test-spoke"
  region           = "West Europe"  
  account          = "test_account"
  resource_group   = "rg-test-spoke"
  cidr = "10.55.141.0/24"

  transit_gw       = "test-transit"
  attached = false  
}
```
Thanks!
BR/Espen T.

**Comment by Dennizz** [comment]
Hi Espen, is this behavior consistent across multiple applies and in different regions? I'm wondering if this may be a transient issue with the Azure API not completing the instance build.

**Comment by gitet** [comment]
Hi Dennis, thanks for the quick reply - I will test in another region ASAP - will report back when done.

**Comment by gitet** [comment]
Update: Tried deploying to "North Europe" - same result I'm afraid. 
Inspecting the resource group via Azure portal: **all the resources are there** + state of gateways is "up" in the aviatrix controller after approx. 8 minutes or so. 

Terraform apply will not exit gracefully with control-c (it just keeps on waiting for the module to finish), so I break out using control-c once more. 
I end up with a terraform state with no reference at all to the gateways. If I remove the gateways manually (controller UI), then comment out the module instance in my tf file, I can clean up the resources with a terraform plan+apply.

I also tried deploying to another subscription, same problem.

**Comment by gitet** [comment]
So I went ahead and tried to deploy using the "raw" resource providers.
Primary gateway (`resource "aviatrix_spoke_gateway" "test_spoke_gateway"`) deploys OK:

```terraform
[...]
aviatrix_spoke_gateway.test_spoke_gateway: Still creating... [3m40s elapsed]
aviatrix_spoke_gateway.test_spoke_gateway: Still creating... [3m50s elapsed]
aviatrix_spoke_gateway.test_spoke_gateway: Still creating... [4m0s elapsed]
aviatrix_spoke_gateway.test_spoke_gateway: Creation complete after 4m5s [id=test-spoke-gw-1]
```

But the ha-gateway (`resource "aviatrix_spoke_ha_gateway" "test_spoke_gateway_ha"`) does not complete:
```terraform
[...]
aviatrix_spoke_ha_gateway.test_spoke_gateway_ha: Still creating... [9m0s elapsed]
aviatrix_spoke_ha_gateway.test_spoke_gateway_ha: Still creating... [9m10s elapsed]
aviatrix_spoke_ha_gateway.test_spoke_gateway_ha: Still creating... [9m20s elapsed]
aviatrix_spoke_ha_gateway.test_spoke_gateway_ha: Still creating... [9m30s elapsed]
```

Again, the controller UI shows the hagw with state = Up, all the expected resources have been deployed in the resource group.

@Dennizz 
There error must be related to the resource provider `aviatrix_spoke_ha_gateway` - should I raise an issue for this under the corresponding repo instead?

**Comment by Dennizz** [comment]
Hi Espen,

With the code that you provided, this doesn't make sense to me. By default `group_mode` is false. In which case, there should be no `aviatrix_spoke_ha_gateway` resource created. Can you share the plan where you are experiencing the issue?

**Comment by gitet** [comment]
Hi Dennis, sure - here's the relevant code snippets I tried (using plain resource providers):

```terraform
# VNET:
resource "aviatrix_vpc" "vnet_test_spoke" {
  cloud_type           = 8
  account_name         = data.aviatrix_account.test_account.account_name
  region               = "West Europe"
  resource_group       = azurerm_resource_group.rg_test_spoke.name
  name                 = "vnet-test-spoke"
  cidr                 = "10.55.141.0/24"
  aviatrix_transit_vpc = false
  aviatrix_firenet_vpc = false
}

# primary gw:
resource "aviatrix_spoke_gateway" "test_spoke_gateway" {
  cloud_type        = 8
  account_name      = data.aviatrix_account.test_account.account_name
  gw_name           = "test-spoke-gw-1"
  vpc_id            = format("%s:%s", aviatrix_vpc.vnet_test_spoke.name, aviatrix_vpc.vnet_test_spoke.resource_group)
  vpc_reg           = "West Europe"
  gw_size           = "Standard_B1ms"
  subnet            = "10.55.141.0/28"
  zone              = "az-1"
  single_ip_snat    = false
  manage_ha_gateway = false
}

# hagw:
resource "aviatrix_spoke_ha_gateway" "test_spoke_gateway_ha" {
  primary_gw_name = aviatrix_spoke_gateway.test_spoke_gateway.id
  gw_name         = "test-spoke-gw-1-hagw"
  gw_size         = "Standard_B1ms"
  subnet          = "10.55.141.0/28"
  # zone            = "az-2"
}
```
The VNET is deployed, the primary gateway and the seconday gateways are also deployed, but `terraform apply` does not finish, because it is waiting for the hagw resource provider to return.

**Comment by gitet** [comment]
Hi @Dennizz - you are probably right about your (out-of-band) comment about our corporate firewall/proxy causing this error. 
I tried running the terraform on a box that does not have our corporate firewall in the traffic path - it worked like a charm. I will close this ticket now.
