### ISSUE TITLE
enable_vpc_dns_server spoke_gateway attribute not exposed

### ISSUE THREAD

**Issue by astipkovits** [terraform-aviatrix-modules/terraform-aviatrix-mc-spoke#21]
Hello Dennis,

The spoke gateway's enable_vpc_dns_server attribute is not exposed and it defaults to false, however if you enable distributed FQDN filtering on the local spoke gateway, the controller sets this value to true. Any further terraform runs that try to set it back to false, fail, becuse you cannot set it to false if you have FQDN filtering configured on the gateway. 

The ask is to expose this parameter of the spoke gateway in the module.

Thanks,
Adam

**Comment by Dennizz** [comment]
Added support for this in 1.6.4!

Thanks for raising this.

Dennis
