### ISSUE TITLE
update format of vNet ID in Azure

### ISSUE THREAD

**Issue by Sevenlive** [terraform-aviatrix-modules/terraform-aviatrix-mc-spoke#23]
As mentioned in [18](https://github.com/terraform-aviatrix-modules/terraform-aviatrix-mc-spoke/issues/18) the format should be <vnet_name>:<resource_group_name>:<vnet_guid>

although it has been fixed in [fdff9110](https://github.com/terraform-aviatrix-modules/terraform-aviatrix-mc-spoke/commit/fdff9110a1754418ea4595f46d28c3c3ac00fdd6) for the azure_greenfield_customized_spoke. Its still wrong for the existing vnet spoke example. Would really appreciate it being fixed.

**Comment by Sevenlive** [comment]
I open the PR #24 to fix it

**Comment by Dennizz** [comment]
Thanks, I appreciate your PR. This looks good. I have merged it and it will be part of the next release.
