### ISSUE TITLE
Support tunnel_count when attach spoke to transit

### ISSUE THREAD

**Issue by jye-aviatrix** [terraform-aviatrix-modules/terraform-aviatrix-mc-spoke#26]
https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs/resources/aviatrix_spoke_transit_attachment

[tunnel_count](https://registry.terraform.io/providers/AviatrixSystems/aviatrix/latest/docs/resources/aviatrix_spoke_transit_attachment#tunnel_count) - (Optional) Number of public tunnels. Required with both Spoke and Transit to be insane mode enabled and max performance enabled. Type: Integer. Valid Range: 1-49. Available as of provider version R3.1.3+.

**Comment by Dennizz** [comment]
This is already in the master branch, just not yet released. Will be part of next release. Feel free to test directly against master and report any issues.
