### ISSUE TITLE
terraform plan results in "nullable" argument errors

### ISSUE THREAD

**Issue by mnoorman** [terraform-aviatrix-modules/terraform-aviatrix-mc-spoke#7]
I want to upgrade my TF version/providers and also use the mc-spoke and transit modules. The 'terraform validate' goes okay, but when I perform the 'terraform plan' I receive many of these errors: "An argument named "nullable" is not expected here."

Looking at the variables files in the modules many of these arguments are present.

My versions:

  required_providers {
    aviatrix = {
      source  = "aviatrixsystems/aviatrix"
      version = "~> 2.22.1"
    }
    aws = {
      source  = "hashicorp/aws"
      version = ">= 4.19"
    }
  }
  required_version = ">= 1.0"
}

mc-transit: 2.1.5
mc-spoke: 1.2.3

**Comment by ragaaviatrix** [comment]
Please check your terraform version. 1.1.0 or newer should fix this issue.

terraform {
  required_providers {
    aviatrix = {
      source  = "aviatrixsystems/aviatrix"
      version = "2.22.0"
    }
  }
  required_version = ">= 1.1.0"
}

**Comment by Dennizz** [comment]
Yes, please use 1.1.0. I forgot to set the module constraint right. Will be there in future release.
