### ISSUE TITLE
Network Domain is not re-associated when going from HPE -> Non-HPE or Non-HPE -> HPE

### ISSUE THREAD

**Issue by bhp-aviatrix** [terraform-aviatrix-modules/terraform-aviatrix-mc-spoke#8]
When moving from HPE -> Non-HPE or Non-HPE -> HPE, the Spoke is detached from Transit, gateways are destroyed, new gateways are created, and then Spoke is re-attached to Transit.  

When re-attaching Spoke to Transit, the assignment of the Network Domain is not occurring.

**Comment by Dennizz** [comment]
Fixed in version 1.3.2
