### ISSUE TITLE
Downsizing HPE Enabled Gateways (c5n.xl -> t3.medium w/ HPE) - Gives Error (does not detach spoke)

### ISSUE THREAD

**Issue by bhp-aviatrix** [terraform-aviatrix-modules/terraform-aviatrix-mc-spoke#9]
When downsizing gateways that are HPE Enabled, where the number of HPE Tunnels decreases - there is a need to detach the spoke prior to resizing the gateway.  

When attempting this via the mc-spoke module, the following error was given when downsizing from c5n.xl -> t3.medium:

module.mc-spoke["spoke6"].aviatrix_spoke_gateway.default: Still modifying... [id=bhp-mcna-lab-aws-use2-test, 10s elapsed]
╷
│ Error: failed to update Aviatrix Spoke Gateway: rest API edit_gw_config Post failed: Error: [AVXERR-GATEWAY-0042] Failed to resize Gateway bhp-mcna-lab-aws-use2-test. Resizing bhp-mcna-lab-aws-use2-test need to release 9 secondary IPs, it only has 0 free.
│ 
│   with module.mc-spoke["spoke6"].aviatrix_spoke_gateway.default,
│   on .terraform/modules/mc-spoke/main.tf line 36, in resource "aviatrix_spoke_gateway" "default":
│   36: resource "aviatrix_spoke_gateway" "default" {
│ 
╵

**Comment by Dennizz** [comment]
Looks like this is a corner case scenario. Normally gateway resizing is possible without detaching the spoke (and this is desired for network availability). However, when downscaling an instance size in insane mode, the controller logic seems to require the release of IP's before removing the amount of tunnels (while attached) that would be decreased by downscaling, yielding this error.

To catch this corner case in controller logic would be the wrong place to try to do it in this module (if at all possible, it's hard to create the logic to only detach in this specific corner case). Please open a change request for controller logic if this needs to be resolved. Sounds to me like an order of operations issue, to allow downsizing an insane mode gateway, while attached.

Alternatively, on the module set attached = false before resizing. Remove this after resizing to reattach. Although a manual action, I believe this to be an acceptable workaround.
